# Generated by Django 4.2.2 on 2025-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='hora_confirmada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
